package com.agent.model;

import java.util.List;
import lombok.Data;

/**
 * Represents a sequence of steps generated by the AI to fulfill a user's query.
 * This plan is a high-level blueprint that the {@code ExecutionEngine} will follow.
 * <p>
 * Lombok's {@code @Data} annotation generates standard boilerplate code.
 */
@Data
public class ExecutionPlan {

    /**
     * An ordered list of {@link ExecutionStep} objects that constitute the plan.
     * The steps are intended to be executed in the order they appear in this list.
     */
    private List<ExecutionStep> steps;
}