package com.agent.service.api;

import com.agent.model.ExecutionPlan;
import com.fasterxml.jackson.databind.JsonNode;
import org.jline.reader.LineReader; // Import LineReader

public interface ExecutionEngine {

    /**
     * Executes a plan generated by the AI.
     * @param plan The execution plan.
     * @param alias The alias for the API, used to retrieve credentials.
     * @param lineReader The JLine LineReader to prompt for user input if needed.
     * @return The final JSON result of the last step in the plan.
     */
    JsonNode execute(ExecutionPlan plan, String alias, LineReader lineReader);
}